### ISSUE TITLE
Cloning into 'cruddy'... Permission denied (publickey). fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by adis-io** [lazychaser/cruddy-app#1]
I had to delete the folder of the submodule. Do 

```
git submodule sync
```

and then

```
git submodule update --init
```

[from here](http://stackoverflow.com/questions/8197089/fatal-error-when-updating-submodule-using-git#comment29217909_8197296)

**Comment by lazychaser** [comment]
I've updated .gitmodules. Thanks.
